docs/ABAC.mdx, docs/Adapters.mdx, docs/Dispatchers.mdx, docs/Effector.mdx, docs/FrontendUsage.mdx, docs/LogError.mdx, docs/OnlineEditor.mdx, docs/Performance.mdx, docs/RBAC.mdx, docs/RBACWithDomainsAPI.mdx, docs/RBACWithPattern.mdx, docs/SyntaxForModels.mdx
Such this:
look in crowdin:
And maybe cause error (https://casbin.io/zh/docs/effector/) :
=> fix: Avoid admonition's format error in crowdin

docs/Function.mdx
Add docs for `keyGet3` 
PR: https://github.com/casbin/casbin/pull/1050
I also separate the table for `KeyMatch*` and `KeyGet*` to make it more clear.
=> docs: add keyGet3

docs/Function.mdx
https://deploy-preview-64--casbin.netlify.app/docs/function#functions-in-matchers
=> fix: C syntax highlighting in function.mdx

docs/SyntaxForModels.mdx
=> fix: the hierarchy in SyntaxForModels.mdx

.github/workflows/pdf.yml
close: #68 
Preview: https://github.com/Selflocking/casbin-website-v2/releases/tag/pdf
ci use [docusaurus-prince-pdf](https://github.com/signcl/docusaurus-prince-pdf) to generate pdf. When successfully built, ci will remove the release tagged pdf (if exists), and create a new release tagged pdf
=> feat: Export docs to PDF

docs/RoleManagerApi.mdx
add docs for PR casbin/casbin#1078
The docs for the set functions may be a bit vague, since where did `rm` come from is not explained.
It seems that `setNamedRoleManager` is not implemented in node-casbin.
=> docs: add docs for GetNamedRoleManager & SetNamedRoleManager

docs/SyntaxForModels.mdx
Docs for the order of matchers' expression really matters.
Fix: https://github.com/casbin/casbin/issues/1161
=> feat: add order for matchers expression

src/css/custom.css
Fix: https://github.com/casbin/casbin-website-v2/issues/153
Previously, the Sidebar had a bug that prevented it from expanding properly, only allowing it to collapse. This PR fixes the issue and adds the functionality for the Sidebar to expand as expected. Users can now conveniently expand or collapse the Sidebar as needed. Thank you for reviewing!
[casbinFix.webm](https://user-images.githubusercontent.com/72064600/231044090-4e63a295-20f5-44ca-a504-e10a05755967.webm)
=> fix: Sidebar expand button made visible

docs/RBACAPI.mdx
fix: https://github.com/casbin/casbin/issues/1233
add `GetImplicitUsersForPermission`
doc about: https://github.com/casbin/casbin/pull/1230 (already merged)
add `GetAllowedObjectConditions`
=> feat: GetImplicitUsersForPermission, GetAllowedObjectConditions

yarn.lock
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
=> chore: update caniuse-lite to latest

.github/workflows/markdownlint.yml
fix: https://github.com/casbin/casbin-website-v2/actions/runs/7006528641/job/19059450937?pr=216
=> ci: use fixed version of markdownlint-cli

docs/RBACWithDomainsAPI.mdx
Add missing method `GetAllRolesByDomain` to docs (included in package but not in docs, see https://github.com/casbin/casbin/blob/master/rbac_api_with_domains.go)
=> docs: add GetAllRolesByDomain() API to docs

docs/Service.mdx
I would like to start by expressing my admiration for Casbin. The dedication and hard work that have gone into it are truly commendable.
With that respect in mind, I am reaching out to request the removal of the link to my now-discontinued project, [Buttress](https://github.com/merajsahebdar/buttress-server). While it was an honor to be part of the Casbin ecosystem, the project is no longer active or maintained, and its presence might mislead users to outdated or unsupported resources.
To maintain the integrity and relevance of the Casbin ecosystem, I believe removing this link would be beneficial. I have made the necessary changes in this pull request, ensuring that only the specific link is affected and all other aspects of the project remain intact. I am open to any suggestions or …
=> docs: remove buttress service

docs/HowItWorks.mdx
I think it's better to replace 'SHOULD' by 'MUST'.
In the context of guidelines, recommendations, or requirements, "must" and "should" have distinct levels of obligation or expectation:
- **Must** indicates a requirement, obligation, or something that is mandatory. It's used when there's no room for discretion or deviation from the directive. In legal or formal contexts, "must" signifies an absolute requirement.
- **Should** suggests a recommendation or advice that is strongly encouraged but not mandatory. It implies that there are reasons or benefits to follow the guidance, but it's not an absolute requirement. There may be acceptable reasons or circumstances to deviate from a "should" directive.
So, when you see "must," think of it as a non-negotiable rule, whereas "should" is more of a …
=> docs: fix wording in "How it works" page

src/pages/editor.js
When refreshing the page, the React component will re-render. However, the useColorMode hook may have retrieved the color mode before the iframe's URL updates. This can lead to the iframe using an old or default theme.
=> fix: fix dark mode not updated bug

src/tableData/AdapterData/AdapterNodejsData.js
Adds a 3rd party adapter I've made for node casbin using mongodb's native driver for node.
[npm](https://www.npmjs.com/package/mongodb-casbin-adapter)
[repo](https://github.com/NathanBhanji/mongodb-casbin-adapter)
https://github.com/casbin/casbin-website-v2/issues/267
=> docs: add Nodejs's mongodb adapter to adapter list

LICENSE
This pull request updates the copyright information in the contributing guidelines file. The placeholder for the year and owner has been replaced with the correct year (2025) and the Casbin Organization as the copyright owner.
**Changes made:**
- Updated the copyright line from:
```
Copyright [yyyy] [name of copyright owner]
```
to:
```
Copyright 2025 Casbin Organization
```
This update ensures that the contributing guidelines reflect the current year and the correct copyright owner.
=> fix: update copyright year and owner in contributing guidelines

docs/LogError.mdx
For PR: https://github.com/casbin/pycasbin/pull/376
modify logging usage desc for casbin and pyCasbin
split usage description of logging for Golang casbin and Python casbin
=> feat: improve docs about PyCasbin logging

docs/CommandLineTools.mdx
fix: modify format of CommandLineTools.mdx
❌ File 'docs/CommandLineTools.mdx'
❌ Wrong parameters: 
<key: storageId, code: fileInvalid, message: MDX file is invalid in line 88, column 15. Message: Could not parse expression with acorn: Unexpected content after expression>
=> fix: modify format of CommandLineTools.mdx

src/tableData/AdapterData/AdapterGoData.js
I've created a new PostgreSQL adapter using the pgx driver that features customizable column count capability. This allows users to define policy tables with more or fewer columns than the standard six fields, which can be useful in various production scenarios.
Regarding implementation, I noticed the `UpdateFilteredPolicies` interface isn't clearly documented. Could someone please explain how this method should behave, what it's expected to return, and some use cases? I haven't implemented it yet as I'm not certain about its intended functionality.
=> feat: add Pgx Adapter to the ecosystem list
