docs/RoleManagerApi.mdx
This PR adds python code snippet on RoleManager API docs page for add_named_matching_func methods
=> feat: Add addnamedmatchingfunc python example

docs/GetStarted.mdx
Added C++ commands in Get Started page
=> feat: added cpp in get-started

src/pages/index.js
=> fix: Add Open Collective

src/pages/index.js
Fix: https://github.com/casbin/casbin-website-v2/issues/31
Signed-off-by: Shivansh-yadav13 <yadavshivansh@gmail.com>
=> fix: homepage text style

docusaurus.config.js
=> fix: Fix algolia search

docusaurus.config.js
Fix: https://github.com/casbin/casbin-website-v2/issues/15
=> fix: Add badges in footer

docs/Adapters.mdx, docs/AdminPortal.mdx, docs/Adopters.mdx, docs/Benchmark.mdx, docs/CasbinRBACAndRBAC96.mdx, docs/CloudNative.mdx, docs/DataPermissions.mdx, docs/Dispatchers.mdx, docs/Effector.mdx, docs/Enforcers.mdx, docs/EnvoyAuthz.mdx, docs/FrontendUsage.mdx, docs/Function.mdx, docs/GetStarted.mdx, docs/GraphQLMiddlewares.mdx, docs/LogError.mdx, docs/ManagementAPI.mdx, docs/Middlewares.mdx, docs/RBACAPI.mdx, docs/RBACWithDomainsAPI.mdx, docs/RBACWithPattern.mdx, docs/RoleManagerApi.mdx, docs/RoleManagers.mdx, docs/SyntaxForModels.mdx, docs/Tutorial.mdx, docs/Watchers.mdx, src/theme/MDXComponents/index.js
=> feat: Syncing tab choices

blog/2021-08-19-apisix-casbin-authorization.md, docs/ABAC.mdx, docs/FrontendUsage.mdx, docs/GetStarted.mdx, docs/SyntaxForModels.mdx, docs/Tutorial.mdx, docusaurus.config.js
Part for: #49 
- Added syntax highlighting for various languages including `ini` and `csv`
=> feat: Added syntax highlighting

docs/ManagementAPI.mdx, docs/PriorityModel.mdx, docs/RBAC.mdx, docs/RBACWithDomains.mdx
add docs for PR https://github.com/casbin/casbin/pull/1041
fix https://github.com/casbin/casbin/pull/1044#issuecomment-1171967131
=> docs: add docs for SetFieldIndex&GetFieldIndex

src/pages/index.js
Signed-off-by: Shivansh-yadav13 <yadavshivansh@gmail.com>
**BEFORE**
**AFTER**
=> fix: mobile logo alignment

package.json, yarn.lock
fix: #57 
The latest docusaurus is [2.0.0-rc.1](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-rc.1)
=> feat: Update docusaurus to the latest

docusaurus.config.js, src/css/custom.css
=> feat: Improve announcementBar style

src/css/custom.css, src/pages/index.js, src/pages/users/index.js
=> fix: Showcase show more logos in one line

docs/Middlewares.mdx
fix https://github.com/casbin/tyk-authz/pull/2#issuecomment-1183371093
=> docs: add tyk-authz

docs/Watchers.mdx
=> docs: fix pycasbin-redis-watcher

docusaurus.config.js
=> fix: Incorrect highlighting in navbar

.github/workflows/pdf.yml
=> fix: Draft releases is generated by default

docusaurus.config.js
Preview: https://casbin.yunshu.site/
=> feat: Edit this page will jump to Crowdin when using non-English

docs/Middlewares.mdx
fix: https://github.com/pycasbin/django-authorization/issues/4
=> docs: add django-authorization

src/pages/casbin-editor.js, src/pages/editor.js
=> fix: Redirect makes editor page not displayed

package.json, src/pages/editor.js, src/theme/BlogPostPaginator/index.js, src/theme/DocPaginator/index.js, yarn.lock
=> refactor: Switch to Giscus commenting system

docs/K8sGateKeeper.mdx, sidebars.js
Fix: https://github.com/casbin/k8s-gatekeeper/issues/18
=> docs: add doc for casbin k8s-gatekeeper

docs/Middlewares.mdx
Request to add `axum-casbin-auth` and `poem-casbin` to middlewares list on the official website
=> feat: Update Middlewares.mdx

docusaurus.config.js
=> fix: switch to new algolia application

docs/Adapters.mdx
Add DynamoDB adapter for Rust to documentation
=> feat: Add DynamoDB adapter for Rust

docs/Tutorial.mdx
https://casbin.io/docs/tutorials
=> fix: tabitem in Tutorial

package.json, yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v2.2.0
=> chore: upgrade docusaurus to 2.2.0

src/pages/index.js, static/data/users.json
=> fix: heighten OpenCollective on mobile

docs/Watchers.mdx
I wrote a Go implementation for Casbin Watcher based on PostgreSQL, please reference https://github.com/IguteChung/casbin-psql-watcher
=> docs: add postgres watcher for Go

docusaurus.config.js, src/components/NavbarItems/Casdoor.js
Refer to: https://github.com/casdoor/casdoor-website/issues/420
=> refactor: use the single demo site

docs/GetStarted.mdx
fixed a simple gramatical mistake
=> docs: fix minor typo

docs/APIOverview.mdx, docs/ManagementAPI.mdx
fix: https://github.com/casbin/casbin-website-v2/issues/149
=> feat: add AddEx API

docs/RBACAPI.mdx, docs/RBACWithDomainsAPI.mdx
docs for https://github.com/casbin/casbin/pull/1245
=> feat: add docs for new APIs: GetImplicitUsersForResource() and GetImplicitUsersForResourceByDomain()

package.json, yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v2.4.1
=> chore: upgrade docusaurus to 2.4.1

docs/Middlewares.mdx
a part of https://github.com/casbin-cpp/nginx-casbin-module/issues/2
=> feat: add nginx-casbin-module

docs/Watchers.mdx
Add python rabbitmq watcher
For: https://github.com/pycasbin/rabbitmq-watcher/pull/1
=> docs: Update Watchers.mdx

docs/Tutorial.mdx
https://github.com/casbin/casbin-website-v2/actions/runs/5494465677
=> docs: update a link

docs/GetStarted.mdx
https://github.com/casbin/casbin/discussions/1147#discussioncomment-6458732
=> docs: fix wrong code

docusaurus.config.js, src/css/custom.css
1. hide navbar when the user scrolls down
2. change the background color of the announcementBar to a solid color
3. add dropdown box in navbar
=> feat: improve website experience

docs/LogError.mdx
Add more information about logger in pycasbin.
=> docs: Update LogError.mdx

docs/Tutorial.mdx
https://github.com/casbin/casbin-website-v2/actions/runs/5700413835/job/15450229537
=> docs: update unavailable tutorial link

docs/Benchmark.mdx
Add benchmark result for pycabin
=> docs: Update Benchmark.mdx

docs/Enforcers.mdx
Update Enforcers.mdx for pycasbin. Add AsyncEnforcer and FastEnforcer.
=> docs: Update Enforcers.mdx for pycasbin

.github/workflows/docs.links.check.config.json
https://github.com/casbin/casbin-website-v2/actions/runs/6676894791/job/18146405197
=> docs: ignore check csdn links

docs/Watchers.mdx
docs: add an Async redis Watcher
=> docs: add an Async redis Watcher

docs/MenuPermissions.mdx, sidebars.js
Create a new scenarios sidebar, then add a menu-permission doc and relocate data-permissions doc.
=> docs: add docs for menu permissions

docs/Middlewares.mdx
=> fix:format Middlewares.mdx

src/pages/editor.js
fix: editor-iframe height too low
=> fix: editor-iframe height too low

src/tableData/AdapterData/AdapterGoData.js
I made [an adapter for Bun ORM](https://github.com/JunNishimura/casbin-bun-adapter)!
In this PR, I have added the Bun adapter to the supported adapters listed in the Casbin documentation. I would appreciate it if you check that out!
=> docs: add reference to Bun Adapter

src/css/custom.css, src/pages/editor.js
Fix: https://github.com/casbin/casbin-website-v2/issues/246
=> fix: Support auto full-screen in iframe

src/pages/editor.js
fix:https://github.com/casbin/casbin-editor/issues/145
=> fix: the editor language doesn't follow the casbin-website language

src/tableData/AdapterData/AdapterRustData.js
For: https://github.com/casbin-rs/string-adapter
=> feat: Add Rust's String Adapter.

src/tableData/AdapterData/AdapterJavaData.js
chore: Update MongoDB Adapter plugin links and image paths in JS file
=> feat: update jcasbin-mongo-adapter repo path

docs/CommandLineTools.mdx, sidebars.js
Fix: https://github.com/casbin-rs/casbin-rust-cli/issues/11
=> docs: add docs for command-line tools

src/tableData/WatcherData/WatcherJavaData.js
feat: add Redis WatcherEx and PostgreSQL Watcher on WatcherJavaData.js
=> feat: add Redis WatcherEx and PostgreSQL Watcher for jcasbin

docs/RBACAPI.mdx
For: https://github.com/casbin/casbin/pull/1523
=> feat: add docs for GetNamedImplicitUsersForResource API
